# Site settings
title: Bowen Li's Blog
email: 
description: ""
baseurl: ""
url: "https://bowen0701.github.io"
twitter_username: bowenli0701
github_username: bowen0701
linkedin_username: bowenli0701

# Build settings
markdown: kramdown
permalink: pretty

highlighter: rouge
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge

theme: jekyll-theme-cayman